remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: German for English Speakers
description: A structured German course for beginners

url: "https://chriiisiscoding.github.io/"
baseurl: "german-prep"

logo: "assets/logo.jpg"
