title: German for English Speakers
description: A structured German course for beginners

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

# optional but recommended
search_enabled: true

url: "https://chriiisiscoding.github.io/"
baseurl: "german-prep"

logo: "assets/logo.jpg"
