title: German for English Speakers
description: A structured German course for beginners

theme: just-the-docs

url: "https://chriiisiscoding.github.io/"
baseurl: "german-prep"

logo: "assets/logo.jpg"
